
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/salus
    username: salus
    password: salus
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    time-zone: Europe/Moscow
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: https://salus.the-omnia.ru/api/v3/login/oauth2/code/google
            client-id: 718112450871-9pevjd7871b5e6oc4i1e6vvpqv102lij.apps.googleusercontent.com
            client-secret: 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


#server:
#  port: 443
#  ssl:
#    enabled: true
#    key-store-type: PKCS12
#    key-store: /etc/letsencrypt/live/involutio.the-omnia.ru

logging:
  file:
    name: ./logs/application.log
  pattern:
    #    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  level:
    org.springframework: info
    root: error
    com.omnia: info


